# A Docker Compose example that starts HttPlaceholder with a MariaDB database, so all stubs (that are made through the UI or API) and requests are saved to the database.
version: '3.8'
services:
  httplaceholder:
    depends_on:
      - postgres
    image: dukeofharen/httplaceholder:latest
    environment:
      postgresConnectionString: 'Host=postgres,5432;Username=postgres;Password=postgres;Database=httplaceholder;SearchPath=public'
      verbose: 'true'
      dev: true
    ports:
      - "5000:5000"
    restart: on-failure
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: httplaceholder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: