//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttPlaceholder.DataLogic.Db {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MysqlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MysqlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HttPlaceholder.DataLogic.Db.MysqlResources", typeof(MysqlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Table structure for table `requests` */
        ///CREATE TABLE IF NOT EXISTS `requests` (
        ///  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
        ///  `correlation_id` VARCHAR(100) NOT NULL,
        ///  `executing_stub_id` VARCHAR(100) DEFAULT NULL,
        ///  `request_begin_time` DATETIME NOT NULL,
        ///  `request_end_time` DATETIME DEFAULT NULL,
        ///  `json` LONGTEXT NOT NULL,
        ///  PRIMARY KEY (`id`),
        ///  UNIQUE KEY `ix_correlation_id` (`correlation_id`),
        ///  KEY `ix_executing_stub_id` (`executing_stub_id`),
        ///  KEY `ix_request_begin_time` (`request_begi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MigrateScript {
            get {
                return ResourceManager.GetString("MigrateScript", resourceCulture);
            }
        }
    }
}
