/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing ConditionCheckResultDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConditionCheckResultDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConditionCheckResultDto
        //private ConditionCheckResultDto instance;

        public ConditionCheckResultDtoTests()
        {
            // TODO uncomment below to create an instance of ConditionCheckResultDto
            //instance = new ConditionCheckResultDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConditionCheckResultDto
        /// </summary>
        [Fact]
        public void ConditionCheckResultDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConditionCheckResultDto
            //Assert.IsInstanceOfType<ConditionCheckResultDto> (instance, "variable 'instance' is a ConditionCheckResultDto");
        }


        /// <summary>
        /// Test the property 'CheckerName'
        /// </summary>
        [Fact]
        public void CheckerNameTest()
        {
            // TODO unit test for the property 'CheckerName'
        }
        /// <summary>
        /// Test the property 'ConditionValidation'
        /// </summary>
        [Fact]
        public void ConditionValidationTest()
        {
            // TODO unit test for the property 'ConditionValidation'
        }
        /// <summary>
        /// Test the property 'Log'
        /// </summary>
        [Fact]
        public void LogTest()
        {
            // TODO unit test for the property 'Log'
        }

    }

}
