/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing FullStubDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FullStubDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FullStubDto
        //private FullStubDto instance;

        public FullStubDtoTests()
        {
            // TODO uncomment below to create an instance of FullStubDto
            //instance = new FullStubDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FullStubDto
        /// </summary>
        [Fact]
        public void FullStubDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FullStubDto
            //Assert.IsInstanceOfType<FullStubDto> (instance, "variable 'instance' is a FullStubDto");
        }


        /// <summary>
        /// Test the property 'Stub'
        /// </summary>
        [Fact]
        public void StubTest()
        {
            // TODO unit test for the property 'Stub'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
