/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing MetadataDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MetadataDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MetadataDto
        //private MetadataDto instance;

        public MetadataDtoTests()
        {
            // TODO uncomment below to create an instance of MetadataDto
            //instance = new MetadataDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MetadataDto
        /// </summary>
        [Fact]
        public void MetadataDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MetadataDto
            //Assert.IsInstanceOfType<MetadataDto> (instance, "variable 'instance' is a MetadataDto");
        }


        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Fact]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'VariableHandlers'
        /// </summary>
        [Fact]
        public void VariableHandlersTest()
        {
            // TODO unit test for the property 'VariableHandlers'
        }

    }

}
