/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing RequestOverviewDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestOverviewDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestOverviewDto
        //private RequestOverviewDto instance;

        public RequestOverviewDtoTests()
        {
            // TODO uncomment below to create an instance of RequestOverviewDto
            //instance = new RequestOverviewDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestOverviewDto
        /// </summary>
        [Fact]
        public void RequestOverviewDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RequestOverviewDto
            //Assert.IsInstanceOfType<RequestOverviewDto> (instance, "variable 'instance' is a RequestOverviewDto");
        }


        /// <summary>
        /// Test the property 'CorrelationId'
        /// </summary>
        [Fact]
        public void CorrelationIdTest()
        {
            // TODO unit test for the property 'CorrelationId'
        }
        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'ExecutingStubId'
        /// </summary>
        [Fact]
        public void ExecutingStubIdTest()
        {
            // TODO unit test for the property 'ExecutingStubId'
        }
        /// <summary>
        /// Test the property 'StubTenant'
        /// </summary>
        [Fact]
        public void StubTenantTest()
        {
            // TODO unit test for the property 'StubTenant'
        }
        /// <summary>
        /// Test the property 'RequestBeginTime'
        /// </summary>
        [Fact]
        public void RequestBeginTimeTest()
        {
            // TODO unit test for the property 'RequestBeginTime'
        }
        /// <summary>
        /// Test the property 'RequestEndTime'
        /// </summary>
        [Fact]
        public void RequestEndTimeTest()
        {
            // TODO unit test for the property 'RequestEndTime'
        }

    }

}
