/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing RequestParametersDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestParametersDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestParametersDto
        //private RequestParametersDto instance;

        public RequestParametersDtoTests()
        {
            // TODO uncomment below to create an instance of RequestParametersDto
            //instance = new RequestParametersDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestParametersDto
        /// </summary>
        [Fact]
        public void RequestParametersDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RequestParametersDto
            //Assert.IsInstanceOfType<RequestParametersDto> (instance, "variable 'instance' is a RequestParametersDto");
        }


        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'Headers'
        /// </summary>
        [Fact]
        public void HeadersTest()
        {
            // TODO unit test for the property 'Headers'
        }
        /// <summary>
        /// Test the property 'ClientIp'
        /// </summary>
        [Fact]
        public void ClientIpTest()
        {
            // TODO unit test for the property 'ClientIp'
        }

    }

}
