/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing RequestResultDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestResultDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestResultDto
        //private RequestResultDto instance;

        public RequestResultDtoTests()
        {
            // TODO uncomment below to create an instance of RequestResultDto
            //instance = new RequestResultDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestResultDto
        /// </summary>
        [Fact]
        public void RequestResultDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RequestResultDto
            //Assert.IsInstanceOfType<RequestResultDto> (instance, "variable 'instance' is a RequestResultDto");
        }


        /// <summary>
        /// Test the property 'CorrelationId'
        /// </summary>
        [Fact]
        public void CorrelationIdTest()
        {
            // TODO unit test for the property 'CorrelationId'
        }
        /// <summary>
        /// Test the property 'RequestParameters'
        /// </summary>
        [Fact]
        public void RequestParametersTest()
        {
            // TODO unit test for the property 'RequestParameters'
        }
        /// <summary>
        /// Test the property 'StubExecutionResults'
        /// </summary>
        [Fact]
        public void StubExecutionResultsTest()
        {
            // TODO unit test for the property 'StubExecutionResults'
        }
        /// <summary>
        /// Test the property 'StubResponseWriterResults'
        /// </summary>
        [Fact]
        public void StubResponseWriterResultsTest()
        {
            // TODO unit test for the property 'StubResponseWriterResults'
        }
        /// <summary>
        /// Test the property 'ExecutingStubId'
        /// </summary>
        [Fact]
        public void ExecutingStubIdTest()
        {
            // TODO unit test for the property 'ExecutingStubId'
        }
        /// <summary>
        /// Test the property 'StubTenant'
        /// </summary>
        [Fact]
        public void StubTenantTest()
        {
            // TODO unit test for the property 'StubTenant'
        }
        /// <summary>
        /// Test the property 'RequestBeginTime'
        /// </summary>
        [Fact]
        public void RequestBeginTimeTest()
        {
            // TODO unit test for the property 'RequestBeginTime'
        }
        /// <summary>
        /// Test the property 'RequestEndTime'
        /// </summary>
        [Fact]
        public void RequestEndTimeTest()
        {
            // TODO unit test for the property 'RequestEndTime'
        }

    }

}
