/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing StubOverviewDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StubOverviewDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StubOverviewDto
        //private StubOverviewDto instance;

        public StubOverviewDtoTests()
        {
            // TODO uncomment below to create an instance of StubOverviewDto
            //instance = new StubOverviewDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StubOverviewDto
        /// </summary>
        [Fact]
        public void StubOverviewDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StubOverviewDto
            //Assert.IsInstanceOfType<StubOverviewDto> (instance, "variable 'instance' is a StubOverviewDto");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Tenant'
        /// </summary>
        [Fact]
        public void TenantTest()
        {
            // TODO unit test for the property 'Tenant'
        }

    }

}
