/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing StubExecutionResultDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StubExecutionResultDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StubExecutionResultDto
        //private StubExecutionResultDto instance;

        public StubExecutionResultDtoTests()
        {
            // TODO uncomment below to create an instance of StubExecutionResultDto
            //instance = new StubExecutionResultDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StubExecutionResultDto
        /// </summary>
        [Fact]
        public void StubExecutionResultDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StubExecutionResultDto
            //Assert.IsInstanceOfType<StubExecutionResultDto> (instance, "variable 'instance' is a StubExecutionResultDto");
        }


        /// <summary>
        /// Test the property 'StubId'
        /// </summary>
        [Fact]
        public void StubIdTest()
        {
            // TODO unit test for the property 'StubId'
        }
        /// <summary>
        /// Test the property 'Passed'
        /// </summary>
        [Fact]
        public void PassedTest()
        {
            // TODO unit test for the property 'Passed'
        }
        /// <summary>
        /// Test the property 'Conditions'
        /// </summary>
        [Fact]
        public void ConditionsTest()
        {
            // TODO unit test for the property 'Conditions'
        }
        /// <summary>
        /// Test the property 'NegativeConditions'
        /// </summary>
        [Fact]
        public void NegativeConditionsTest()
        {
            // TODO unit test for the property 'NegativeConditions'
        }

    }

}
