/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing StubResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StubResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StubResponseDto
        //private StubResponseDto instance;

        public StubResponseDtoTests()
        {
            // TODO uncomment below to create an instance of StubResponseDto
            //instance = new StubResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StubResponseDto
        /// </summary>
        [Fact]
        public void StubResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StubResponseDto
            //Assert.IsInstanceOfType<StubResponseDto> (instance, "variable 'instance' is a StubResponseDto");
        }


        /// <summary>
        /// Test the property 'EnableDynamicMode'
        /// </summary>
        [Fact]
        public void EnableDynamicModeTest()
        {
            // TODO unit test for the property 'EnableDynamicMode'
        }
        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Base64'
        /// </summary>
        [Fact]
        public void Base64Test()
        {
            // TODO unit test for the property 'Base64'
        }
        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Fact]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }
        /// <summary>
        /// Test the property 'Headers'
        /// </summary>
        [Fact]
        public void HeadersTest()
        {
            // TODO unit test for the property 'Headers'
        }
        /// <summary>
        /// Test the property 'ExtraDuration'
        /// </summary>
        [Fact]
        public void ExtraDurationTest()
        {
            // TODO unit test for the property 'ExtraDuration'
        }
        /// <summary>
        /// Test the property 'Json'
        /// </summary>
        [Fact]
        public void JsonTest()
        {
            // TODO unit test for the property 'Json'
        }
        /// <summary>
        /// Test the property 'Xml'
        /// </summary>
        [Fact]
        public void XmlTest()
        {
            // TODO unit test for the property 'Xml'
        }
        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Fact]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }
        /// <summary>
        /// Test the property 'TemporaryRedirect'
        /// </summary>
        [Fact]
        public void TemporaryRedirectTest()
        {
            // TODO unit test for the property 'TemporaryRedirect'
        }
        /// <summary>
        /// Test the property 'PermanentRedirect'
        /// </summary>
        [Fact]
        public void PermanentRedirectTest()
        {
            // TODO unit test for the property 'PermanentRedirect'
        }
        /// <summary>
        /// Test the property 'ReverseProxy'
        /// </summary>
        [Fact]
        public void ReverseProxyTest()
        {
            // TODO unit test for the property 'ReverseProxy'
        }

    }

}
