/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing StubResponseImageDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StubResponseImageDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StubResponseImageDto
        //private StubResponseImageDto instance;

        public StubResponseImageDtoTests()
        {
            // TODO uncomment below to create an instance of StubResponseImageDto
            //instance = new StubResponseImageDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StubResponseImageDto
        /// </summary>
        [Fact]
        public void StubResponseImageDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StubResponseImageDto
            //Assert.IsInstanceOfType<StubResponseImageDto> (instance, "variable 'instance' is a StubResponseImageDto");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'BackgroundColor'
        /// </summary>
        [Fact]
        public void BackgroundColorTest()
        {
            // TODO unit test for the property 'BackgroundColor'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'FontSize'
        /// </summary>
        [Fact]
        public void FontSizeTest()
        {
            // TODO unit test for the property 'FontSize'
        }
        /// <summary>
        /// Test the property 'FontColor'
        /// </summary>
        [Fact]
        public void FontColorTest()
        {
            // TODO unit test for the property 'FontColor'
        }
        /// <summary>
        /// Test the property 'JpegQuality'
        /// </summary>
        [Fact]
        public void JpegQualityTest()
        {
            // TODO unit test for the property 'JpegQuality'
        }
        /// <summary>
        /// Test the property 'WordWrap'
        /// </summary>
        [Fact]
        public void WordWrapTest()
        {
            // TODO unit test for the property 'WordWrap'
        }

    }

}
