/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing StubXpathDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StubXpathDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StubXpathDto
        //private StubXpathDto instance;

        public StubXpathDtoTests()
        {
            // TODO uncomment below to create an instance of StubXpathDto
            //instance = new StubXpathDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StubXpathDto
        /// </summary>
        [Fact]
        public void StubXpathDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StubXpathDto
            //Assert.IsInstanceOfType<StubXpathDto> (instance, "variable 'instance' is a StubXpathDto");
        }


        /// <summary>
        /// Test the property 'QueryString'
        /// </summary>
        [Fact]
        public void QueryStringTest()
        {
            // TODO unit test for the property 'QueryString'
        }
        /// <summary>
        /// Test the property 'Namespaces'
        /// </summary>
        [Fact]
        public void NamespacesTest()
        {
            // TODO unit test for the property 'Namespaces'
        }

    }

}
