/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing StubBasicAuthenticationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StubBasicAuthenticationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StubBasicAuthenticationDto
        //private StubBasicAuthenticationDto instance;

        public StubBasicAuthenticationDtoTests()
        {
            // TODO uncomment below to create an instance of StubBasicAuthenticationDto
            //instance = new StubBasicAuthenticationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StubBasicAuthenticationDto
        /// </summary>
        [Fact]
        public void StubBasicAuthenticationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StubBasicAuthenticationDto
            //Assert.IsInstanceOfType<StubBasicAuthenticationDto> (instance, "variable 'instance' is a StubBasicAuthenticationDto");
        }


        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

    }

}
