/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing StubResponseReverseProxyDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StubResponseReverseProxyDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StubResponseReverseProxyDto
        //private StubResponseReverseProxyDto instance;

        public StubResponseReverseProxyDtoTests()
        {
            // TODO uncomment below to create an instance of StubResponseReverseProxyDto
            //instance = new StubResponseReverseProxyDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StubResponseReverseProxyDto
        /// </summary>
        [Fact]
        public void StubResponseReverseProxyDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StubResponseReverseProxyDto
            //Assert.IsInstanceOfType<StubResponseReverseProxyDto> (instance, "variable 'instance' is a StubResponseReverseProxyDto");
        }


        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'AppendQueryString'
        /// </summary>
        [Fact]
        public void AppendQueryStringTest()
        {
            // TODO unit test for the property 'AppendQueryString'
        }
        /// <summary>
        /// Test the property 'AppendPath'
        /// </summary>
        [Fact]
        public void AppendPathTest()
        {
            // TODO unit test for the property 'AppendPath'
        }
        /// <summary>
        /// Test the property 'ReplaceRootUrl'
        /// </summary>
        [Fact]
        public void ReplaceRootUrlTest()
        {
            // TODO unit test for the property 'ReplaceRootUrl'
        }

    }

}
