/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing StubUrlConditionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StubUrlConditionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StubUrlConditionDto
        //private StubUrlConditionDto instance;

        public StubUrlConditionDtoTests()
        {
            // TODO uncomment below to create an instance of StubUrlConditionDto
            //instance = new StubUrlConditionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StubUrlConditionDto
        /// </summary>
        [Fact]
        public void StubUrlConditionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StubUrlConditionDto
            //Assert.IsInstanceOfType<StubUrlConditionDto> (instance, "variable 'instance' is a StubUrlConditionDto");
        }


        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }
        /// <summary>
        /// Test the property 'FullPath'
        /// </summary>
        [Fact]
        public void FullPathTest()
        {
            // TODO unit test for the property 'FullPath'
        }
        /// <summary>
        /// Test the property 'IsHttps'
        /// </summary>
        [Fact]
        public void IsHttpsTest()
        {
            // TODO unit test for the property 'IsHttps'
        }

    }

}
