/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing StubResponseWriterResultDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StubResponseWriterResultDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StubResponseWriterResultDto
        //private StubResponseWriterResultDto instance;

        public StubResponseWriterResultDtoTests()
        {
            // TODO uncomment below to create an instance of StubResponseWriterResultDto
            //instance = new StubResponseWriterResultDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StubResponseWriterResultDto
        /// </summary>
        [Fact]
        public void StubResponseWriterResultDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StubResponseWriterResultDto
            //Assert.IsInstanceOfType<StubResponseWriterResultDto> (instance, "variable 'instance' is a StubResponseWriterResultDto");
        }


        /// <summary>
        /// Test the property 'ResponseWriterName'
        /// </summary>
        [Fact]
        public void ResponseWriterNameTest()
        {
            // TODO unit test for the property 'ResponseWriterName'
        }
        /// <summary>
        /// Test the property 'Executed'
        /// </summary>
        [Fact]
        public void ExecutedTest()
        {
            // TODO unit test for the property 'Executed'
        }
        /// <summary>
        /// Test the property 'Log'
        /// </summary>
        [Fact]
        public void LogTest()
        {
            // TODO unit test for the property 'Log'
        }

    }

}
