/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HttPlaceholder.Client.Api;
using HttPlaceholder.Client.Model;
using HttPlaceholder.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HttPlaceholder.Client.Test
{
    /// <summary>
    ///  Class for testing VariableHandlerDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VariableHandlerDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VariableHandlerDto
        //private VariableHandlerDto instance;

        public VariableHandlerDtoTests()
        {
            // TODO uncomment below to create an instance of VariableHandlerDto
            //instance = new VariableHandlerDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VariableHandlerDto
        /// </summary>
        [Fact]
        public void VariableHandlerDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VariableHandlerDto
            //Assert.IsInstanceOfType<VariableHandlerDto> (instance, "variable 'instance' is a VariableHandlerDto");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'Example'
        /// </summary>
        [Fact]
        public void ExampleTest()
        {
            // TODO unit test for the property 'Example'
        }

    }

}
