variables:
  DEBIAN_IMAGE: debian:stable-slim
  PWSH_IMAGE: mcr.microsoft.com/powershell:latest
  DOTNET_IMAGE: mcr.microsoft.com/dotnet/core/sdk:3.1
  NODE_IMAGE: node:lts-alpine3.9

stages:
  - prepare-version
  - prebuild
  - test
  - build-ui
  - build-server
  - install
  - deploy

set-version:
  image: $DEBIAN_IMAGE
  stage: prepare-version
  script:
    - chmod +x ./scripts/build/set-version.sh
    - ./scripts/build/set-version.sh "$CI_PIPELINE_IID"
  artifacts:
    paths:
      - version.txt

patch-csproj-versions:
  image: $PWSH_IMAGE
  stage: prebuild
  script:
    - VERSION="$(cat version.txt)"
    - pwsh scripts/build/patch-csproj-versions.ps1 -srcFolder src

#test:
#  image: $DOTNET_IMAGE
#  stage: test
#  script:
#    - cd src
#    - dotnet test

build-ui:
  image: $NODE_IMAGE
  stage: build-ui
  script:
    - chmod +x ./scripts/build/build-ui.sh
    - sh ./scripts/build/build-ui.sh

build-windows:
  image: $DOTNET_IMAGE
  stage: build-server
  script:
    - chmod +x ./scripts/build/build-windows.sh
    - ./scripts/build/build-windows.sh