image: Visual Studio 2017

before_build:
  - cmd: choco install dotnetcore-sdk
  - cmd: dotnet --version
  - ps: Get-ChildItem -Path "C:\Program Files\dotnet\sdk"

environment:
  access_token:
    secure: Zcoti9GsS4Y1t12qVcWhfDXMJLW8QLt4SdeQi8VKUFBtd/gVyWsZlLXDOHLP8i5U
  nuget_api_key:
    secure: DkwNpTFW5LR/MS5rp1wi2wBHQPhntAH+waI41ytZ0+3oVt9q9Txuv0CRrslv3rgj

branches:
  only:
    - nothing

build_script:
  - git submodule update --init --recursive
  - ps: scripts\bootstrap.ps1

test: off

skip_tags: true

artifacts:
  - path: dist\**
    name: httplaceholder
    type: zip

deploy:
  release: $(RELEASE_NAME)
  description: $(RELEASE_DESCRIPTION)
  provider: GitHub
  auth_token: $(access_token)
  draft: true
  prerelease: $(RELEASE_IS_PRERELEASE)