image: Visual Studio 2017

before_build:
  - cmd: dotnet --version
  - ps: Get-ChildItem -Path "C:\Program Files\dotnet\sdk"
  - ps: scripts\Determine-Variables.ps1
  - ps: scripts\Patch-Versions.ps1

environment:
  access_token:
    secure: Zcoti9GsS4Y1t12qVcWhfDXMJLW8QLt4SdeQi8VKUFBtd/gVyWsZlLXDOHLP8i5U
  nuget_api_key:
    secure: /spG2CSTqaB6JnDd2aJouT744+d81tM4LTeYLd7kE3DJA7dBpuSOPEZ30kjwTpEr

branches:
  only:
    - dev

build_script:
  - git submodule update --init --recursive
  - ps: scripts\Build.ps1

test: off

skip_tags: true

artifacts:
  - path: src\HttPlaceholder\bin\release\netcoreapp2.2\win10-x64\publish\httplaceholder_*.exe
    name: httplaceholder-windows
    type: zip
  - path: src\HttPlaceholder.Client\bin\Release\*.nupkg
    name: httplaceholder-nuget
    type: zip
  - path: src\HttPlaceholder\bin\Tool\*.nupkg
    name: httplaceholder-tool
    type: zip
  - path: '**\swagger.json'
    name: swagger
    type: zip
  - path: src\HttPlaceholder\bin\release\netcoreapp2.2\httplaceholder_*.zip
    name: httplaceholder-zips
    type: zip
  - path: src\HttPlaceholder\bin\release\netcoreapp2.2\httplaceholder_*.tar.gz
    name: httplaceholder-tars
    type: zip

deploy:
  release: $(releaseName)
  description: $(description)
  provider: GitHub
  auth_token: $(access_token)
  draft: $(draft)
  prerelease: $(prerelease)