before_build:
  - cmd: dotnet --version
  - ps: Get-ChildItem -Path "C:\Program Files\dotnet\sdk"
  - ps: scripts\Determine-Variables.ps1
  - ps: scripts\Patch-Versions.ps1

environment:
  access_token:
    secure: Zcoti9GsS4Y1t12qVcWhfDXMJLW8QLt4SdeQi8VKUFBtd/gVyWsZlLXDOHLP8i5U

branches:
  only:
    - dev
    - master

build_script:
  - git submodule update --init --recursive
  - ps: scripts\Build.ps1

test: off

skip_tags: true

artifacts:
  - path: src\HttPlaceholder\bin\release\netcoreapp2.1\win10-x64\publish\httplaceholder_*.exe
    name: armyknife-windows
    type: zip
  - path: '**\swagger.json'
    name: swagger
    type: zip

deploy:
  release: $(releaseName)
  description: $(description)
  provider: GitHub
  auth_token: $(access_token)
  draft: $(draft)
  prerelease: $(prerelease)