version: '3.7'
services:
  httplaceholder:
    build: .
    environment:
      fileStorageLocation: /var/stubs
      oldRequestsQueueLength: 300
      verbose: true
    volumes:
      - stubs:/var/stubs
    ports:
      - "8080:5000"
      - "4430:5050"

volumes:
  stubs: