//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttPlaceholder.Application.Configuration {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigKeysResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigKeysResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HttPlaceholder.Application.Configuration.ConfigKeysResources", typeof(ConfigKeysResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ApiUsername {
            get {
                return ResourceManager.GetString("ApiUsername", resourceCulture);
            }
        }
        
        internal static string ApiPassword {
            get {
                return ResourceManager.GetString("ApiPassword", resourceCulture);
            }
        }
        
        internal static string HttpsPort {
            get {
                return ResourceManager.GetString("HttpsPort", resourceCulture);
            }
        }
        
        internal static string InputFile {
            get {
                return ResourceManager.GetString("InputFile", resourceCulture);
            }
        }
        
        internal static string DisableFileWatcher {
            get {
                return ResourceManager.GetString("DisableFileWatcher", resourceCulture);
            }
        }
        
        internal static string OldRequestsQueueLength {
            get {
                return ResourceManager.GetString("OldRequestsQueueLength", resourceCulture);
            }
        }
        
        internal static string StoreResponses {
            get {
                return ResourceManager.GetString("StoreResponses", resourceCulture);
            }
        }
        
        internal static string CleanOldRequestsInBackgroundJob {
            get {
                return ResourceManager.GetString("CleanOldRequestsInBackgroundJob", resourceCulture);
            }
        }
        
        internal static string PfxPassword {
            get {
                return ResourceManager.GetString("PfxPassword", resourceCulture);
            }
        }
        
        internal static string ReadProxyHeaders {
            get {
                return ResourceManager.GetString("ReadProxyHeaders", resourceCulture);
            }
        }
        
        internal static string SafeProxyIps {
            get {
                return ResourceManager.GetString("SafeProxyIps", resourceCulture);
            }
        }
        
        internal static string PfxPath {
            get {
                return ResourceManager.GetString("PfxPath", resourceCulture);
            }
        }
        
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        internal static string UseHttps {
            get {
                return ResourceManager.GetString("UseHttps", resourceCulture);
            }
        }
        
        internal static string PublicUrl {
            get {
                return ResourceManager.GetString("PublicUrl", resourceCulture);
            }
        }
        
        internal static string EnableRequestLogging {
            get {
                return ResourceManager.GetString("EnableRequestLogging", resourceCulture);
            }
        }
        
        internal static string FileStorageLocation {
            get {
                return ResourceManager.GetString("FileStorageLocation", resourceCulture);
            }
        }
        
        internal static string UseInMemoryStorage {
            get {
                return ResourceManager.GetString("UseInMemoryStorage", resourceCulture);
            }
        }
        
        internal static string MysqlConnectionString {
            get {
                return ResourceManager.GetString("MysqlConnectionString", resourceCulture);
            }
        }
        
        internal static string SqliteConnectionString {
            get {
                return ResourceManager.GetString("SqliteConnectionString", resourceCulture);
            }
        }
        
        internal static string SqlServerConnectionString {
            get {
                return ResourceManager.GetString("SqlServerConnectionString", resourceCulture);
            }
        }
        
        internal static string PostrgresConnectionString {
            get {
                return ResourceManager.GetString("PostrgresConnectionString", resourceCulture);
            }
        }
        
        internal static string EnableUserInterface {
            get {
                return ResourceManager.GetString("EnableUserInterface", resourceCulture);
            }
        }
        
        internal static string MaximumExtraDurationMillis {
            get {
                return ResourceManager.GetString("MaximumExtraDurationMillis", resourceCulture);
            }
        }
        
        internal static string HealthcheckOnRootUrl {
            get {
                return ResourceManager.GetString("HealthcheckOnRootUrl", resourceCulture);
            }
        }
        
        internal static string AllowGlobalFileSearch {
            get {
                return ResourceManager.GetString("AllowGlobalFileSearch", resourceCulture);
            }
        }
        
        internal static string ConfigJsonLocation {
            get {
                return ResourceManager.GetString("ConfigJsonLocation", resourceCulture);
            }
        }
    }
}
