//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Placeholder.Tests.Integration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IntegrationTestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IntegrationTestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Placeholder.Tests.Integration.IntegrationTestResources", typeof(IntegrationTestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - id: postcode-eelde
        ///  conditions:
        ///    method: GET
        ///    url:
        ///      path: \blocatieserver\/v3\/suggest\b
        ///      query:
        ///        q: 9761BP
        ///  negativeConditions:
        ///    url:
        ///      query:
        ///        filter: postcode
        ///  response:
        ///    text: &apos;{&quot;response&quot;:{&quot;numFound&quot;:23,&quot;start&quot;:0,&quot;maxScore&quot;:18.281225,&quot;docs&quot;:[{&quot;type&quot;:&quot;postcode&quot;,&quot;weergavenaam&quot;:&quot;Kluivingskampenweg, 9761BP Eelde&quot;,&quot;id&quot;:&quot;pcd-bdae7c76ab31b82843622995d7fc6dc0&quot;,&quot;score&quot;:18.281225},{&quot;type&quot;:&quot;adres&quot;,&quot;weergavenaam&quot;:&quot;Kluivingskampenweg 2, 9761BP Eelde&quot;,&quot;id&quot;:&quot;ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestYamlFile {
            get {
                return ResourceManager.GetString("TestYamlFile", resourceCulture);
            }
        }
    }
}
