export const mutationNames = {
  userTokenMutation: "storeUserToken",
  storeDarkTheme: "storeDarkTheme",
  storeMetadata: "storeMetadata",
  storeStubQueryStrings: "storeStubQueryStrings",
  storeQueryStrings: "storeQueryStrings",
  storeStubIsHttpsSelected: "storeStubIsHttpsSelected",
  storeIsHttpsSelected: "storeIsHttpsSelected",
  storeStubHeaders: "storeStubHeaders",
  storeHeaders: "storeHeaders",
  storeStubBody: "storeStubBody",
  storeBody: "storeBody",
  storeStubFormBody: "storeStubFormBody",
  storeFormBody: "storeFormBody",
  storeStubXPathAndNamespaces: "storeStubXPathAndNamespaces",
  storeXPathAndNamespaces: "storeXPathAndNamespaces",
  storeStubJsonPath: "storeStubJsonPath",
  storeJsonPath: "storeJsonPath",
  storeResponseBodyType: "storeResponseBodyType",
  storeStubResponseBodyType: "storeStubResponseBodyType",
  storeStubResponseHeaders: "storeStubResponseHeaders",
  storeResponseHeaders: "storeResponseHeaders",
  clearStubForm: "clearStubForm",
  setResponseHeader: "setResponseHeader"
};

export const actionNames = {
  addStubs: "addStubs",
  getStubsOverview: "getStubsOverview",
  getTenantNames: "getTenantNames",
  authenticate: "authenticate",
  getRequestsOverview: "getRequestsOverview",
  getRequest: "getRequest",
  clearRequests: "clearRequests",
  deleteAllStubs: "deleteAllStubs",
  getStub: "getStub",
  updateStub: "updateStub",
  createStubBasedOnRequest: "createStubBasedOnRequest",
  deleteStub: "deleteStub",
  ensureAuthenticated: "ensureAuthenticated",
  getMetadata: "getMetadata"
};
