# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.synced_folder "./../..", "/httplaceholder"
  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.box_version = "2202.0.2404"
  config.vm.network :forwarded_port, guest: 5000, host: 8080

  config.vm.provider "virtualbox" do |vb, override|
    vb.memory = "4096"
    vb.cpus = 2
    vb.gui = true
  end
end
