/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HttPlaceholder.Client.Client.OpenAPIDateConverter;

namespace HttPlaceholder.Client.Model
{
    /// <summary>
    /// A class for storing a stripped down version of a stub with metadata.
    /// </summary>
    [DataContract]
    public partial class FullStubOverviewDto :  IEquatable<FullStubOverviewDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FullStubOverviewDto" /> class.
        /// </summary>
        /// <param name="stub">Gets or sets the stub..</param>
        /// <param name="metadata">Gets or sets the metadata..</param>
        public FullStubOverviewDto(StubOverviewDto stub = default(StubOverviewDto), StubMetadataDto metadata = default(StubMetadataDto))
        {
            this.Stub = stub;
            this.Metadata = metadata;
        }
        
        /// <summary>
        /// Gets or sets the stub.
        /// </summary>
        /// <value>Gets or sets the stub.</value>
        [DataMember(Name="stub", EmitDefaultValue=true)]
        public StubOverviewDto Stub { get; set; }

        /// <summary>
        /// Gets or sets the metadata.
        /// </summary>
        /// <value>Gets or sets the metadata.</value>
        [DataMember(Name="metadata", EmitDefaultValue=true)]
        public StubMetadataDto Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FullStubOverviewDto {\n");
            sb.Append("  Stub: ").Append(Stub).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FullStubOverviewDto);
        }

        /// <summary>
        /// Returns true if FullStubOverviewDto instances are equal
        /// </summary>
        /// <param name="input">Instance of FullStubOverviewDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FullStubOverviewDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Stub == input.Stub ||
                    (this.Stub != null &&
                    this.Stub.Equals(input.Stub))
                ) && 
                (
                    this.Metadata == input.Metadata ||
                    (this.Metadata != null &&
                    this.Metadata.Equals(input.Metadata))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Stub != null)
                    hashCode = hashCode * 59 + this.Stub.GetHashCode();
                if (this.Metadata != null)
                    hashCode = hashCode * 59 + this.Metadata.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
