/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HttPlaceholder.Client.Client.OpenAPIDateConverter;

namespace HttPlaceholder.Client.Model
{
    /// <summary>
    /// A model for storing the HttPlaceholder metadata.
    /// </summary>
    [DataContract]
    public partial class MetadataDto :  IEquatable<MetadataDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MetadataDto" /> class.
        /// </summary>
        /// <param name="version">Gets or sets the version..</param>
        /// <param name="variableHandlers">Gets or sets the available variable handlers..</param>
        public MetadataDto(string version = default(string), List<VariableHandlerDto> variableHandlers = default(List<VariableHandlerDto>))
        {
            this.Version = version;
            this.VariableHandlers = variableHandlers;
        }
        
        /// <summary>
        /// Gets or sets the version.
        /// </summary>
        /// <value>Gets or sets the version.</value>
        [DataMember(Name="version", EmitDefaultValue=true)]
        public string Version { get; set; }

        /// <summary>
        /// Gets or sets the available variable handlers.
        /// </summary>
        /// <value>Gets or sets the available variable handlers.</value>
        [DataMember(Name="variableHandlers", EmitDefaultValue=true)]
        public List<VariableHandlerDto> VariableHandlers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MetadataDto {\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("  VariableHandlers: ").Append(VariableHandlers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MetadataDto);
        }

        /// <summary>
        /// Returns true if MetadataDto instances are equal
        /// </summary>
        /// <param name="input">Instance of MetadataDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MetadataDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Version == input.Version ||
                    (this.Version != null &&
                    this.Version.Equals(input.Version))
                ) && 
                (
                    this.VariableHandlers == input.VariableHandlers ||
                    this.VariableHandlers != null &&
                    input.VariableHandlers != null &&
                    this.VariableHandlers.SequenceEqual(input.VariableHandlers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Version != null)
                    hashCode = hashCode * 59 + this.Version.GetHashCode();
                if (this.VariableHandlers != null)
                    hashCode = hashCode * 59 + this.VariableHandlers.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
