/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HttPlaceholder.Client.Client.OpenAPIDateConverter;

namespace HttPlaceholder.Client.Model
{
    /// <summary>
    /// A model for storing a request.
    /// </summary>
    [DataContract]
    public partial class RequestResultDto :  IEquatable<RequestResultDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestResultDto" /> class.
        /// </summary>
        /// <param name="correlationId">Gets or sets the correlation identifier..</param>
        /// <param name="requestParameters">Gets or sets the request parameters..</param>
        /// <param name="stubExecutionResults">Gets or sets the stub execution results..</param>
        /// <param name="stubResponseWriterResults">Gets or sets the stub response writer results..</param>
        /// <param name="executingStubId">Gets or sets the executing stub identifier..</param>
        /// <param name="stubTenant">Gets or sets the tenant name of the stub..</param>
        /// <param name="requestBeginTime">Gets or sets the request begin time..</param>
        /// <param name="requestEndTime">Gets or sets the request end time..</param>
        public RequestResultDto(string correlationId = default(string), RequestParametersDto requestParameters = default(RequestParametersDto), List<StubExecutionResultDto> stubExecutionResults = default(List<StubExecutionResultDto>), List<StubResponseWriterResultDto> stubResponseWriterResults = default(List<StubResponseWriterResultDto>), string executingStubId = default(string), string stubTenant = default(string), DateTime requestBeginTime = default(DateTime), DateTime requestEndTime = default(DateTime))
        {
            this.CorrelationId = correlationId;
            this.RequestParameters = requestParameters;
            this.StubExecutionResults = stubExecutionResults;
            this.StubResponseWriterResults = stubResponseWriterResults;
            this.ExecutingStubId = executingStubId;
            this.StubTenant = stubTenant;
            this.RequestBeginTime = requestBeginTime;
            this.RequestEndTime = requestEndTime;
        }
        
        /// <summary>
        /// Gets or sets the correlation identifier.
        /// </summary>
        /// <value>Gets or sets the correlation identifier.</value>
        [DataMember(Name="correlationId", EmitDefaultValue=true)]
        public string CorrelationId { get; set; }

        /// <summary>
        /// Gets or sets the request parameters.
        /// </summary>
        /// <value>Gets or sets the request parameters.</value>
        [DataMember(Name="requestParameters", EmitDefaultValue=true)]
        public RequestParametersDto RequestParameters { get; set; }

        /// <summary>
        /// Gets or sets the stub execution results.
        /// </summary>
        /// <value>Gets or sets the stub execution results.</value>
        [DataMember(Name="stubExecutionResults", EmitDefaultValue=true)]
        public List<StubExecutionResultDto> StubExecutionResults { get; set; }

        /// <summary>
        /// Gets or sets the stub response writer results.
        /// </summary>
        /// <value>Gets or sets the stub response writer results.</value>
        [DataMember(Name="stubResponseWriterResults", EmitDefaultValue=true)]
        public List<StubResponseWriterResultDto> StubResponseWriterResults { get; set; }

        /// <summary>
        /// Gets or sets the executing stub identifier.
        /// </summary>
        /// <value>Gets or sets the executing stub identifier.</value>
        [DataMember(Name="executingStubId", EmitDefaultValue=true)]
        public string ExecutingStubId { get; set; }

        /// <summary>
        /// Gets or sets the tenant name of the stub.
        /// </summary>
        /// <value>Gets or sets the tenant name of the stub.</value>
        [DataMember(Name="stubTenant", EmitDefaultValue=true)]
        public string StubTenant { get; set; }

        /// <summary>
        /// Gets or sets the request begin time.
        /// </summary>
        /// <value>Gets or sets the request begin time.</value>
        [DataMember(Name="requestBeginTime", EmitDefaultValue=false)]
        public DateTime RequestBeginTime { get; set; }

        /// <summary>
        /// Gets or sets the request end time.
        /// </summary>
        /// <value>Gets or sets the request end time.</value>
        [DataMember(Name="requestEndTime", EmitDefaultValue=false)]
        public DateTime RequestEndTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RequestResultDto {\n");
            sb.Append("  CorrelationId: ").Append(CorrelationId).Append("\n");
            sb.Append("  RequestParameters: ").Append(RequestParameters).Append("\n");
            sb.Append("  StubExecutionResults: ").Append(StubExecutionResults).Append("\n");
            sb.Append("  StubResponseWriterResults: ").Append(StubResponseWriterResults).Append("\n");
            sb.Append("  ExecutingStubId: ").Append(ExecutingStubId).Append("\n");
            sb.Append("  StubTenant: ").Append(StubTenant).Append("\n");
            sb.Append("  RequestBeginTime: ").Append(RequestBeginTime).Append("\n");
            sb.Append("  RequestEndTime: ").Append(RequestEndTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RequestResultDto);
        }

        /// <summary>
        /// Returns true if RequestResultDto instances are equal
        /// </summary>
        /// <param name="input">Instance of RequestResultDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RequestResultDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CorrelationId == input.CorrelationId ||
                    (this.CorrelationId != null &&
                    this.CorrelationId.Equals(input.CorrelationId))
                ) && 
                (
                    this.RequestParameters == input.RequestParameters ||
                    (this.RequestParameters != null &&
                    this.RequestParameters.Equals(input.RequestParameters))
                ) && 
                (
                    this.StubExecutionResults == input.StubExecutionResults ||
                    this.StubExecutionResults != null &&
                    input.StubExecutionResults != null &&
                    this.StubExecutionResults.SequenceEqual(input.StubExecutionResults)
                ) && 
                (
                    this.StubResponseWriterResults == input.StubResponseWriterResults ||
                    this.StubResponseWriterResults != null &&
                    input.StubResponseWriterResults != null &&
                    this.StubResponseWriterResults.SequenceEqual(input.StubResponseWriterResults)
                ) && 
                (
                    this.ExecutingStubId == input.ExecutingStubId ||
                    (this.ExecutingStubId != null &&
                    this.ExecutingStubId.Equals(input.ExecutingStubId))
                ) && 
                (
                    this.StubTenant == input.StubTenant ||
                    (this.StubTenant != null &&
                    this.StubTenant.Equals(input.StubTenant))
                ) && 
                (
                    this.RequestBeginTime == input.RequestBeginTime ||
                    (this.RequestBeginTime != null &&
                    this.RequestBeginTime.Equals(input.RequestBeginTime))
                ) && 
                (
                    this.RequestEndTime == input.RequestEndTime ||
                    (this.RequestEndTime != null &&
                    this.RequestEndTime.Equals(input.RequestEndTime))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CorrelationId != null)
                    hashCode = hashCode * 59 + this.CorrelationId.GetHashCode();
                if (this.RequestParameters != null)
                    hashCode = hashCode * 59 + this.RequestParameters.GetHashCode();
                if (this.StubExecutionResults != null)
                    hashCode = hashCode * 59 + this.StubExecutionResults.GetHashCode();
                if (this.StubResponseWriterResults != null)
                    hashCode = hashCode * 59 + this.StubResponseWriterResults.GetHashCode();
                if (this.ExecutingStubId != null)
                    hashCode = hashCode * 59 + this.ExecutingStubId.GetHashCode();
                if (this.StubTenant != null)
                    hashCode = hashCode * 59 + this.StubTenant.GetHashCode();
                if (this.RequestBeginTime != null)
                    hashCode = hashCode * 59 + this.RequestBeginTime.GetHashCode();
                if (this.RequestEndTime != null)
                    hashCode = hashCode * 59 + this.RequestEndTime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
