/* 
 * HttPlaceholder API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HttPlaceholder.Client.Client.OpenAPIDateConverter;

namespace HttPlaceholder.Client.Model
{
    /// <summary>
    /// A model for storing all conditions for a stub.
    /// </summary>
    [DataContract]
    public partial class StubConditionsDto :  IEquatable<StubConditionsDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StubConditionsDto" /> class.
        /// </summary>
        /// <param name="method">Gets or sets the method..</param>
        /// <param name="url">Gets or sets the URL..</param>
        /// <param name="body">Gets or sets the body..</param>
        /// <param name="form">Gets or sets the form..</param>
        /// <param name="headers">Gets or sets the headers..</param>
        /// <param name="xpath">Gets or sets the xpath..</param>
        /// <param name="jsonPath">Gets or sets the json path..</param>
        /// <param name="basicAuthentication">Gets or sets the basic authentication..</param>
        /// <param name="clientIp">Gets or sets the client ip..</param>
        /// <param name="host">Gets or sets the host..</param>
        public StubConditionsDto(string method = default(string), StubUrlConditionDto url = default(StubUrlConditionDto), List<string> body = default(List<string>), List<StubFormDto> form = default(List<StubFormDto>), Dictionary<string, string> headers = default(Dictionary<string, string>), List<StubXpathDto> xpath = default(List<StubXpathDto>), List<string> jsonPath = default(List<string>), StubBasicAuthenticationDto basicAuthentication = default(StubBasicAuthenticationDto), string clientIp = default(string), string host = default(string))
        {
            this.Method = method;
            this.Url = url;
            this.Body = body;
            this.Form = form;
            this.Headers = headers;
            this.Xpath = xpath;
            this.JsonPath = jsonPath;
            this.BasicAuthentication = basicAuthentication;
            this.ClientIp = clientIp;
            this.Host = host;
        }
        
        /// <summary>
        /// Gets or sets the method.
        /// </summary>
        /// <value>Gets or sets the method.</value>
        [DataMember(Name="method", EmitDefaultValue=true)]
        public string Method { get; set; }

        /// <summary>
        /// Gets or sets the URL.
        /// </summary>
        /// <value>Gets or sets the URL.</value>
        [DataMember(Name="url", EmitDefaultValue=true)]
        public StubUrlConditionDto Url { get; set; }

        /// <summary>
        /// Gets or sets the body.
        /// </summary>
        /// <value>Gets or sets the body.</value>
        [DataMember(Name="body", EmitDefaultValue=true)]
        public List<string> Body { get; set; }

        /// <summary>
        /// Gets or sets the form.
        /// </summary>
        /// <value>Gets or sets the form.</value>
        [DataMember(Name="form", EmitDefaultValue=true)]
        public List<StubFormDto> Form { get; set; }

        /// <summary>
        /// Gets or sets the headers.
        /// </summary>
        /// <value>Gets or sets the headers.</value>
        [DataMember(Name="headers", EmitDefaultValue=true)]
        public Dictionary<string, string> Headers { get; set; }

        /// <summary>
        /// Gets or sets the xpath.
        /// </summary>
        /// <value>Gets or sets the xpath.</value>
        [DataMember(Name="xpath", EmitDefaultValue=true)]
        public List<StubXpathDto> Xpath { get; set; }

        /// <summary>
        /// Gets or sets the json path.
        /// </summary>
        /// <value>Gets or sets the json path.</value>
        [DataMember(Name="jsonPath", EmitDefaultValue=true)]
        public List<string> JsonPath { get; set; }

        /// <summary>
        /// Gets or sets the basic authentication.
        /// </summary>
        /// <value>Gets or sets the basic authentication.</value>
        [DataMember(Name="basicAuthentication", EmitDefaultValue=true)]
        public StubBasicAuthenticationDto BasicAuthentication { get; set; }

        /// <summary>
        /// Gets or sets the client ip.
        /// </summary>
        /// <value>Gets or sets the client ip.</value>
        [DataMember(Name="clientIp", EmitDefaultValue=true)]
        public string ClientIp { get; set; }

        /// <summary>
        /// Gets or sets the host.
        /// </summary>
        /// <value>Gets or sets the host.</value>
        [DataMember(Name="host", EmitDefaultValue=true)]
        public string Host { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StubConditionsDto {\n");
            sb.Append("  Method: ").Append(Method).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  Form: ").Append(Form).Append("\n");
            sb.Append("  Headers: ").Append(Headers).Append("\n");
            sb.Append("  Xpath: ").Append(Xpath).Append("\n");
            sb.Append("  JsonPath: ").Append(JsonPath).Append("\n");
            sb.Append("  BasicAuthentication: ").Append(BasicAuthentication).Append("\n");
            sb.Append("  ClientIp: ").Append(ClientIp).Append("\n");
            sb.Append("  Host: ").Append(Host).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StubConditionsDto);
        }

        /// <summary>
        /// Returns true if StubConditionsDto instances are equal
        /// </summary>
        /// <param name="input">Instance of StubConditionsDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StubConditionsDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Method == input.Method ||
                    (this.Method != null &&
                    this.Method.Equals(input.Method))
                ) && 
                (
                    this.Url == input.Url ||
                    (this.Url != null &&
                    this.Url.Equals(input.Url))
                ) && 
                (
                    this.Body == input.Body ||
                    this.Body != null &&
                    input.Body != null &&
                    this.Body.SequenceEqual(input.Body)
                ) && 
                (
                    this.Form == input.Form ||
                    this.Form != null &&
                    input.Form != null &&
                    this.Form.SequenceEqual(input.Form)
                ) && 
                (
                    this.Headers == input.Headers ||
                    this.Headers != null &&
                    input.Headers != null &&
                    this.Headers.SequenceEqual(input.Headers)
                ) && 
                (
                    this.Xpath == input.Xpath ||
                    this.Xpath != null &&
                    input.Xpath != null &&
                    this.Xpath.SequenceEqual(input.Xpath)
                ) && 
                (
                    this.JsonPath == input.JsonPath ||
                    this.JsonPath != null &&
                    input.JsonPath != null &&
                    this.JsonPath.SequenceEqual(input.JsonPath)
                ) && 
                (
                    this.BasicAuthentication == input.BasicAuthentication ||
                    (this.BasicAuthentication != null &&
                    this.BasicAuthentication.Equals(input.BasicAuthentication))
                ) && 
                (
                    this.ClientIp == input.ClientIp ||
                    (this.ClientIp != null &&
                    this.ClientIp.Equals(input.ClientIp))
                ) && 
                (
                    this.Host == input.Host ||
                    (this.Host != null &&
                    this.Host.Equals(input.Host))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Method != null)
                    hashCode = hashCode * 59 + this.Method.GetHashCode();
                if (this.Url != null)
                    hashCode = hashCode * 59 + this.Url.GetHashCode();
                if (this.Body != null)
                    hashCode = hashCode * 59 + this.Body.GetHashCode();
                if (this.Form != null)
                    hashCode = hashCode * 59 + this.Form.GetHashCode();
                if (this.Headers != null)
                    hashCode = hashCode * 59 + this.Headers.GetHashCode();
                if (this.Xpath != null)
                    hashCode = hashCode * 59 + this.Xpath.GetHashCode();
                if (this.JsonPath != null)
                    hashCode = hashCode * 59 + this.JsonPath.GetHashCode();
                if (this.BasicAuthentication != null)
                    hashCode = hashCode * 59 + this.BasicAuthentication.GetHashCode();
                if (this.ClientIp != null)
                    hashCode = hashCode * 59 + this.ClientIp.GetHashCode();
                if (this.Host != null)
                    hashCode = hashCode * 59 + this.Host.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
