/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/bootstrap/Accordion.vue')['default']
    AccordionButton: typeof import('./src/components/bootstrap/AccordionButton.vue')['default']
    AccordionItem: typeof import('./src/components/bootstrap/AccordionItem.vue')['default']
    BasicAuthHelper: typeof import('./src/components/stubForm/formHelper/BasicAuthHelper.vue')['default']
    BasicInput: typeof import('./src/components/stubForm/formHelper/BasicInput.vue')['default']
    BinaryBody: typeof import('./src/components/request/body/BinaryBody.vue')['default']
    CodeEditor: typeof import('./src/components/codemirror/CodeEditor.vue')['default']
    CodeHighlight: typeof import('./src/components/hljs/CodeHighlight.vue')['default']
    ExampleSelector: typeof import('./src/components/stubForm/formHelper/ExampleSelector.vue')['default']
    FormHelperSelector: typeof import('./src/components/stubForm/formHelper/FormHelperSelector.vue')['default']
    HttpMethodSelector: typeof import('./src/components/stubForm/formHelper/HttpMethodSelector.vue')['default']
    HttpStatusCodeSelector: typeof import('./src/components/stubForm/formHelper/HttpStatusCodeSelector.vue')['default']
    ImportCurl: typeof import('./src/components/import/ImportCurl.vue')['default']
    ImportHar: typeof import('./src/components/import/ImportHar.vue')['default']
    ImportOpenApi: typeof import('./src/components/import/ImportOpenApi.vue')['default']
    LineEndingSelector: typeof import('./src/components/stubForm/formHelper/LineEndingSelector.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Method: typeof import('./src/components/request/Method.vue')['default']
    Modal: typeof import('./src/components/bootstrap/Modal.vue')['default']
    QueryParams: typeof import('./src/components/request/QueryParams.vue')['default']
    RedirectSelector: typeof import('./src/components/stubForm/formHelper/RedirectSelector.vue')['default']
    RenderedFormHelper: typeof import('./src/components/stubForm/formHelper/RenderedFormHelper.vue')['default']
    Request: typeof import('./src/components/request/Request.vue')['default']
    RequestDetails: typeof import('./src/components/request/RequestDetails.vue')['default']
    RequestExport: typeof import('./src/components/request/RequestExport.vue')['default']
    RequestHeaders: typeof import('./src/components/request/RequestHeaders.vue')['default']
    RequestResponse: typeof import('./src/components/request/RequestResponse.vue')['default']
    RequestResponseBody: typeof import('./src/components/request/body/RequestResponseBody.vue')['default']
    ResponseBodyHelper: typeof import('./src/components/stubForm/formHelper/ResponseBodyHelper.vue')['default']
    ResponseWriterResults: typeof import('./src/components/request/ResponseWriterResults.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenarioSelector: typeof import('./src/components/stubForm/formHelper/ScenarioSelector.vue')['default']
    SetDynamicMode: typeof import('./src/components/stubForm/formHelper/SetDynamicMode.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarMenuItem: typeof import('./src/components/SidebarMenuItem.vue')['default']
    SimpleEditor: typeof import('./src/components/simpleEditor/SimpleEditor.vue')['default']
    StringCheckerInput: typeof import('./src/components/stubForm/formHelper/StringCheckerInput.vue')['default']
    Stub: typeof import('./src/components/stub/Stub.vue')['default']
    StubExecutionResult: typeof import('./src/components/request/StubExecutionResult.vue')['default']
    StubExecutionResults: typeof import('./src/components/request/StubExecutionResults.vue')['default']
    StubFormButtons: typeof import('./src/components/stubForm/StubFormButtons.vue')['default']
    TenantSelector: typeof import('./src/components/stubForm/formHelper/TenantSelector.vue')['default']
    TextBody: typeof import('./src/components/request/body/TextBody.vue')['default']
    UploadButton: typeof import('./src/components/UploadButton.vue')['default']
    UploadStubs: typeof import('./src/components/import/UploadStubs.vue')['default']
    VariableHandlerSelector: typeof import('./src/components/stubForm/formHelper/VariableHandlerSelector.vue')['default']
    Vue3SlideUpDown: typeof import('vue3-slide-up-down')['Vue3SlideUpDown']
    VuePdfEmbed: typeof import('vue-pdf-embed')['default']
  }
}
