# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.synced_folder "./../..", "/httplaceholder"
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.1.8"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 443, host: 4430
  config.vm.provision :shell, path: "bootstrap.sh", privileged: false

  config.vm.provider "virtualbox" do |vb, override|
    vb.name = "httplaceholder-ubuntu-server"
    vb.memory = "2048"
    vb.cpus = 1
    vb.gui = true
  end
end
