---
blank_issues_enabled: false
contact_links:
  - name: HttPlaceholder Community Support
    url: https://github.com/dukeofharen/httplaceholder/discussions
    about: Please ask and answer questions here.
