//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttPlaceholder.Application.StubExecution.ResponseVariableParsingHandlers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseVariableParsingResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseVariableParsingResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HttPlaceholder.Application.StubExecution.ResponseVariableParsingHandlers.Response" +
                            "VariableParsingResources", typeof(ResponseVariableParsingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ClientIp {
            get {
                return ResourceManager.GetString("ClientIp", resourceCulture);
            }
        }
        
        internal static string DisplayUrl {
            get {
                return ResourceManager.GetString("DisplayUrl", resourceCulture);
            }
        }
        
        internal static string FakeData {
            get {
                return ResourceManager.GetString("FakeData", resourceCulture);
            }
        }
        
        internal static string FormPost {
            get {
                return ResourceManager.GetString("FormPost", resourceCulture);
            }
        }
        
        internal static string JsonPath {
            get {
                return ResourceManager.GetString("JsonPath", resourceCulture);
            }
        }
        
        internal static string LocalNow {
            get {
                return ResourceManager.GetString("LocalNow", resourceCulture);
            }
        }
        
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        internal static string QueryEncoded {
            get {
                return ResourceManager.GetString("QueryEncoded", resourceCulture);
            }
        }
        
        internal static string RequestBody {
            get {
                return ResourceManager.GetString("RequestBody", resourceCulture);
            }
        }
        
        internal static string RequestHeader {
            get {
                return ResourceManager.GetString("RequestHeader", resourceCulture);
            }
        }
        
        internal static string RootUrl {
            get {
                return ResourceManager.GetString("RootUrl", resourceCulture);
            }
        }
        
        internal static string ScenarioHitcount {
            get {
                return ResourceManager.GetString("ScenarioHitcount", resourceCulture);
            }
        }
        
        internal static string ScenarioState {
            get {
                return ResourceManager.GetString("ScenarioState", resourceCulture);
            }
        }
        
        internal static string UtcNow {
            get {
                return ResourceManager.GetString("UtcNow", resourceCulture);
            }
        }
        
        internal static string Uuid {
            get {
                return ResourceManager.GetString("Uuid", resourceCulture);
            }
        }
    }
}
