//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttPlaceholder.Application.StubExecution.ResponseVariableParsingHandlers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseVariableParsingResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseVariableParsingResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HttPlaceholder.Application.StubExecution.ResponseVariableParsingHandlers.Response" +
                            "VariableParsingResources", typeof(ResponseVariableParsingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ClientIpDescription {
            get {
                return ResourceManager.GetString("ClientIpDescription", resourceCulture);
            }
        }
        
        internal static string DisplayUrlDescription {
            get {
                return ResourceManager.GetString("DisplayUrlDescription", resourceCulture);
            }
        }
        
        internal static string FakeDataDescription {
            get {
                return ResourceManager.GetString("FakeDataDescription", resourceCulture);
            }
        }
        
        internal static string FormPostDescription {
            get {
                return ResourceManager.GetString("FormPostDescription", resourceCulture);
            }
        }
        
        internal static string JsonPathDescription {
            get {
                return ResourceManager.GetString("JsonPathDescription", resourceCulture);
            }
        }
        
        internal static string LocalNowDescription {
            get {
                return ResourceManager.GetString("LocalNowDescription", resourceCulture);
            }
        }
        
        internal static string QueryDescription {
            get {
                return ResourceManager.GetString("QueryDescription", resourceCulture);
            }
        }
        
        internal static string QueryEncodedDescription {
            get {
                return ResourceManager.GetString("QueryEncodedDescription", resourceCulture);
            }
        }
        
        internal static string RequestBodyDescription {
            get {
                return ResourceManager.GetString("RequestBodyDescription", resourceCulture);
            }
        }
        
        internal static string RequestHeaderDescription {
            get {
                return ResourceManager.GetString("RequestHeaderDescription", resourceCulture);
            }
        }
        
        internal static string RootUrlDescription {
            get {
                return ResourceManager.GetString("RootUrlDescription", resourceCulture);
            }
        }
        
        internal static string ScenarioHitcountDescription {
            get {
                return ResourceManager.GetString("ScenarioHitcountDescription", resourceCulture);
            }
        }
        
        internal static string ScenarioStateDescription {
            get {
                return ResourceManager.GetString("ScenarioStateDescription", resourceCulture);
            }
        }
        
        internal static string UtcNowDescription {
            get {
                return ResourceManager.GetString("UtcNowDescription", resourceCulture);
            }
        }
        
        internal static string UuidDescription {
            get {
                return ResourceManager.GetString("UuidDescription", resourceCulture);
            }
        }
    }
}
