using HttPlaceholder.Common.Utilities;
using HttPlaceholder.Domain;
using Newtonsoft.Json;

namespace HttPlaceholder.Application.Stubs.Utilities;

/// <summary>
///     Utility class that contains several methods for working with stub models.
/// </summary>
public static class StubExtensions
{
    /// <summary>
    ///     Sets an autogenerated ID on a stub if no ID has been set yet.
    /// </summary>
    /// <param name="stub">The stub.</param>
    /// <returns>The stub ID.</returns>
    public static string EnsureStubId(this StubModel stub)
    {
        if (!string.IsNullOrWhiteSpace(stub.Id))
        {
            return stub.Id;
        }

        var id = $"generated-{HashingUtilities.GetMd5String(JsonConvert.SerializeObject(stub))}";
        stub.Id = id;
        return id;
    }
}
