# A Docker Compose example that starts HttPlaceholder with a SQLite database, so all stubs (that are made through the UI or API) and requests are saved to the database.
version: '3.8'
services:
  httplaceholder:
    image: dukeofharen/httplaceholder:latest
    environment:
      sqliteConnectionString: 'Data Source=/etc/httplaceholder/httplaceholder.db'
      verbose: 'true'
      dev: true
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - sqlite_data:/etc/httplaceholder
    
volumes:
  sqlite_data: