ALTER TABLE stubs ADD CONSTRAINT PK_Stubs PRIMARY KEY NONCLUSTERED (id);
ALTER TABLE requests ADD CONSTRAINT PK_Requests PRIMARY KEY NONCLUSTERED (id);
ALTER TABLE metadata ADD CONSTRAINT PK_Metadata PRIMARY KEY NONCLUSTERED (id);
