//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttPlaceholder.Application.StubExecution {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StubResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StubResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HttPlaceholder.Application.StubExecution.StubResources", typeof(StubResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NoAuthHeaderFound {
            get {
                return ResourceManager.GetString("NoAuthHeaderFound", resourceCulture);
            }
        }
        
        internal static string BasicAuthPassed {
            get {
                return ResourceManager.GetString("BasicAuthPassed", resourceCulture);
            }
        }
        
        internal static string BasicAuthFailed {
            get {
                return ResourceManager.GetString("BasicAuthFailed", resourceCulture);
            }
        }
        
        internal static string BodyConditionFailed {
            get {
                return ResourceManager.GetString("BodyConditionFailed", resourceCulture);
            }
        }
        
        internal static string FormValueNotFound {
            get {
                return ResourceManager.GetString("FormValueNotFound", resourceCulture);
            }
        }
        
        internal static string FormConditionFailed {
            get {
                return ResourceManager.GetString("FormConditionFailed", resourceCulture);
            }
        }
        
        internal static string FullPathConditionFailed {
            get {
                return ResourceManager.GetString("FullPathConditionFailed", resourceCulture);
            }
        }
        
        internal static string HeaderConditionFailed {
            get {
                return ResourceManager.GetString("HeaderConditionFailed", resourceCulture);
            }
        }
        
        internal static string JsonTypeNotSupported {
            get {
                return ResourceManager.GetString("JsonTypeNotSupported", resourceCulture);
            }
        }
        
        internal static string JsonPassedItemObjectExpected {
            get {
                return ResourceManager.GetString("JsonPassedItemObjectExpected", resourceCulture);
            }
        }
        
        internal static string JsonNumberOfItemsTooSmall {
            get {
                return ResourceManager.GetString("JsonNumberOfItemsTooSmall", resourceCulture);
            }
        }
        
        internal static string JsonPropertyNotFound {
            get {
                return ResourceManager.GetString("JsonPropertyNotFound", resourceCulture);
            }
        }
        
        internal static string JsonPassedItemArrayExpected {
            get {
                return ResourceManager.GetString("JsonPassedItemArrayExpected", resourceCulture);
            }
        }
        
        internal static string JsonNumberOfItemsDoesntMatch {
            get {
                return ResourceManager.GetString("JsonNumberOfItemsDoesntMatch", resourceCulture);
            }
        }
        
        internal static string JsonInputDoesntCorrespondWithRegexOrSubstring {
            get {
                return ResourceManager.GetString("JsonInputDoesntCorrespondWithRegexOrSubstring", resourceCulture);
            }
        }
        
        internal static string JsonValueInvalidBoolean {
            get {
                return ResourceManager.GetString("JsonValueInvalidBoolean", resourceCulture);
            }
        }
        
        internal static string JsonValueInvalidFloat {
            get {
                return ResourceManager.GetString("JsonValueInvalidFloat", resourceCulture);
            }
        }
        
        internal static string JsonValueInvalidInt {
            get {
                return ResourceManager.GetString("JsonValueInvalidInt", resourceCulture);
            }
        }
        
        internal static string JsonValueInvalidDateTime {
            get {
                return ResourceManager.GetString("JsonValueInvalidDateTime", resourceCulture);
            }
        }
        
        internal static string JsonTokenTypeNotSupported {
            get {
                return ResourceManager.GetString("JsonTokenTypeNotSupported", resourceCulture);
            }
        }
    }
}
