//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttPlaceholder.Client.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HttPlaceholder.Client.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;correlationId&quot;: &quot;ae4ed085-ba9c-4d17-9b4c-57ae50533d8d&quot;,
        ///        &quot;requestParameters&quot;: {
        ///            &quot;method&quot;: &quot;GET&quot;,
        ///            &quot;url&quot;: &quot;http://localhost:5000/&quot;,
        ///            &quot;body&quot;: &quot;&quot;,
        ///            &quot;headers&quot;: {
        ///                &quot;Cache-Control&quot;: &quot;max-age=0&quot;,
        ///                &quot;Connection&quot;: &quot;keep-alive&quot;,
        ///                &quot;Accept&quot;: &quot;text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8&quot;,
        ///                &quot;Accept-Encoding&quot;: &quot;gzip, deflate&quot;,
        ///                &quot;Accept-Language&quot;: &quot;en-US,en;q=0.5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string get_all_requests_example {
            get {
                return ResourceManager.GetString("get_all_requests_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;stub&quot;: {
        ///            &quot;id&quot;: &quot;image&quot;,
        ///            &quot;conditions&quot;: {
        ///                &quot;method&quot;: &quot;GET&quot;,
        ///                &quot;url&quot;: {
        ///                    &quot;path&quot;: &quot;/image.png&quot;
        ///                }
        ///            },
        ///            &quot;response&quot;: {
        ///                &quot;statusCode&quot;: 200,
        ///                &quot;base64&quot;: &quot;iVBORw0KGgoAAAANSUhEUgAABwUAAAFQCAYAAABeYKGWAAAgAElEQVR4nOzdd1yVdf/H8WNluwTOgnMOh8PhiIMtCGJWWKa5J5mZZg7cgoo4cJw0xe5My9Zt9zC34tayZXln7sgZChyQHJn9KpUh48Dh8/sDNJuaieeAr+fj8f6f63tdWPo6Q6EAAAAAAAAAAAAAAAAAAAAAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string get_all_stubs_example {
            get {
                return ResourceManager.GetString("get_all_stubs_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;stub&quot;: {
        ///        &quot;id&quot;: &quot;main-page&quot;,
        ///        &quot;conditions&quot;: {
        ///            &quot;method&quot;: &quot;GET&quot;,
        ///            &quot;url&quot;: {
        ///                &quot;path&quot;: &quot;index.html&quot;
        ///            }
        ///        },
        ///        &quot;response&quot;: {
        ///            &quot;statusCode&quot;: 200,
        ///            &quot;html&quot;: &quot;&lt;html&gt;\n  &lt;head&gt;\n    &lt;title&gt;Test page in HttPlaceholder&lt;/title&gt;\n    &lt;link href=\&quot;/style.css\&quot; rel=\&quot;stylesheet\&quot; /&gt;\n  &lt;/head&gt;\n  &lt;body&gt;\n    &lt;img src=\&quot;/image.png\&quot; /&gt;\n    &lt;h1&gt;Example in HttPlaceholder&lt;/h1&gt;\n    &lt;p&gt;\n      Hey, this is just a proof of con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string get_stub_by_id_example {
            get {
                return ResourceManager.GetString("get_stub_by_id_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;stub&quot;: {
        ///            &quot;id&quot;: &quot;image&quot;,
        ///            &quot;conditions&quot;: {
        ///                &quot;method&quot;: &quot;GET&quot;,
        ///                &quot;url&quot;: {
        ///                    &quot;path&quot;: &quot;/image.png&quot;
        ///                }
        ///            },
        ///            &quot;response&quot;: {
        ///                &quot;statusCode&quot;: 200,
        ///                &quot;base64&quot;: &quot;iVBORw0KGgoAAAANSUhEUgAABwUAAAFQCAYAAABeYKGWAAAgAElEQVR4nOzdd1yVdf/H8WNluwTOgnMOh8PhiIMtCGJWWKa5J5mZZg7cgoo4cJw0xe5My9Zt9zC34tayZXln7sgZChyQHJn9KpUh48Dh8/sDNJuaieeAr+fj8f6f63tdWPo6Q6EAAAAAAAAAAAAAAAAAAAAAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string get_stubs_by_tenant_example {
            get {
                return ResourceManager.GetString("get_stubs_by_tenant_example", resourceCulture);
            }
        }
    }
}
