//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttPlaceholder.Web.Shared.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebSharedResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebSharedResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HttPlaceholder.Web.Shared.Resources.WebSharedResources", typeof(WebSharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CmdExample {
            get {
                return ResourceManager.GetString("CmdExample", resourceCulture);
            }
        }
        
        internal static string ExplanationHeader {
            get {
                return ResourceManager.GetString("ExplanationHeader", resourceCulture);
            }
        }
        
        internal static string VersionHeader {
            get {
                return ResourceManager.GetString("VersionHeader", resourceCulture);
            }
        }
        
        internal static string JobCleanOldRequestsDescription {
            get {
                return ResourceManager.GetString("JobCleanOldRequestsDescription", resourceCulture);
            }
        }
        
        internal static string PortsAlreadyTaken {
            get {
                return ResourceManager.GetString("PortsAlreadyTaken", resourceCulture);
            }
        }
        
        internal static string PortInvalid {
            get {
                return ResourceManager.GetString("PortInvalid", resourceCulture);
            }
        }
        
        internal static string VerboseHeader {
            get {
                return ResourceManager.GetString("VerboseHeader", resourceCulture);
            }
        }
    }
}
