version: '3.8'
services:
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: httplaceholder
      MYSQL_USER: httplaceholder
      MYSQL_PASSWORD: httplaceholder
    ports:
      - "3306:3306"
    volumes:
      - mysql5_data:/var/lib/mysql
  mysql8:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: httplaceholder
      MYSQL_USER: httplaceholder
      MYSQL_PASSWORD: httplaceholder
    ports:
      - "3307:3306"
    volumes:
      - mysql8_data:/var/lib/mysql
  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: httplaceholder
      MYSQL_USER: httplaceholder
      MYSQL_PASSWORD: httplaceholder
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password123!
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./mssql_initscripts:/usr/local/bin/initscripts
    command: /bin/bash /usr/local/bin/initscripts/entrypoint.sh
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: httplaceholder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql5_data:
  mysql8_data:
  mariadb_data:
  mssql_data:
  postgres_data: