# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.synced_folder "./../..", "/vagrant"
  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.network :forwarded_port, guest: 5000, host: 4567
  config.vm.provision :shell, path: "bootstrap.ps1"

  config.vm.provider "virtualbox" do |vb, override|
    vb.name = "vagrant-httplaceholder-windows"
    vb.memory = "4096"
    vb.cpus = 2
    vb.gui = true
  end
end
