version: '3.8'
services:
  httplaceholder:
    image: dukeofharen/httplaceholder:latest
    environment:
      fileStorageLocation: '/etc/httplaceholder'
    ports:
      - 5000:5000
    restart: on-failure
    volumes:
      - stub_data:/etc/httplaceholder

volumes:
  stub_data: