# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.synced_folder "./../../scripts", "/vagrant", type: "rsync"
  config.vm.box = "jhcook/macos-sierra"
  config.vm.network :forwarded_port, guest: 5000, host: 4567

  config.vm.provider "virtualbox" do |vb, override|
    vb.name = "vagrant-httplaceholder-mac"
    vb.memory = "4096"
    vb.cpus = 2
    vb.gui = true
  end
end
